### ISSUE TITLE
Deck vs Collection

### ISSUE THREAD

**Issue by ccusin33** [r0adkll/DeckBox#112]
It would be interesting a feature when I register or Import a Deck that their cards already add to the Collection cards.  why doesn't it happen?

**Comment by r0adkll** [comment]
The intention of the import is to import decks that you may not necessarily have all the cards for in your collection, such as importing the top decks from recent tournaments, or decks of your favorite YouTuber.  I will evaluate adding an option that you can select (such as a checkbox or switch) that will auto-import the cards into your collection, but for now, I'm going to leave these features as is until a later date as I prioritize other features on my roadmap. Thanks for the suggestion, as I will leave this in the backlog
