### ISSUE TITLE
[BUG] Deck tags allow me to add empty tags

### ISSUE THREAD

**Issue by uberhalit** [r0adkll/DeckBox#129]
**Describe the bug**
Deck builder allows to add empty tags.

**To Reproduce**
1. Go to 'Decks'
2. Create a new deck
3. Click on 'Add tags'
4. Click the tag symbol to add it without any content

**Expected behavior**
Simply close the "Add tags" bar without adding an empty tag

**Screenshots**
![01](https://user-images.githubusercontent.com/19159295/89740055-086c2780-da86-11ea-88fd-a7897d21eeae.png)
![02](https://user-images.githubusercontent.com/19159295/89740056-0a35eb00-da86-11ea-9b46-95dfa5bd7e35.png)
**Smartphone:**
 - Device: Samsung Galaxy S8
 - OS: Android 7
 - Version: 1.0.0.880

**Comment by r0adkll** [comment]
See https://github.com/r0adkll/DeckBox/issues/131
