### ISSUE TITLE
[BUG] Swipe sensitivity between tabs is too high

### ISSUE THREAD

**Issue by uberhalit** [r0adkll/DeckBox#130]
**To Reproduce**
1. Go to 'Browse'
2. Open the filter
3. Scroll around a bit, you will often trigger an unwanted swipe

**Smartphone:**
 - Device: Galaxy S8
 - OS: Android 7.0
 - Version 1.0.0.880

**Comment by r0adkll** [comment]
See https://github.com/r0adkll/DeckBox/issues/131
