### ISSUE TITLE
[FEATURE] Add an UNLIMITED format or an option to globally remove all warnings/errors in deck building

### ISSUE THREAD

**Issue by uberhalit** [r0adkll/DeckBox#131]
Me and my friends are playing an oldshool GX format (basically everything that got released before Synchros) that extends GOAT format by a lot. Every deck I import will have multiple warnings about cards that are banned/limited/not legal etc. Further I can not export any deck that got 'invalidated' by such a warning.

**Describe the solution you'd like**
A simple UNLIMITED format option would solve this, the best thing would be a custom banlist/format editor/importer though.

**Describe alternatives you've considered**
Globally suppress all of these warnings/errors in settings.

**Additional context**
![03](https://user-images.githubusercontent.com/19159295/89740348-1d49ba80-da88-11ea-82f2-d4fc391a83a5.png)
![04](https://user-images.githubusercontent.com/19159295/89740350-1fac1480-da88-11ea-9053-9db364cbb349.png)

**Comment by r0adkll** [comment]
This is the repository for DeckBox, the pokemon variant of my deck building applications. The DeckTin repo is not open source at this moment, but we are already tracking your requests on that repository, Thanks!

**Comment by uberhalit** [comment]
> This is the repository for DeckBox, the pokemon variant of my deck building applications. The DeckTin repo is not open source at this moment, but we are already tracking your requests on that repository, Thanks!

Oh I am very sorry, I came here from inside the YGO app itself so I thought it was the right place. Should I do the other reports via mail instead?
