### ISSUE TITLE
[FEATURE] Custom format/banlist editor

### ISSUE THREAD

**Issue by uberhalit** [r0adkll/DeckBox#132]
Basically the dream or every veteran/oldschool player that plays with friends only. The ability to create a custom format list would enable this app to operate under any player base.

**Describe the solution you'd like**
An editor similar to the deck builder but instead of filling deck, side and extra deck one'd fill **forbidden**, **limited** and **semi-limited** (and potentially "**unlimited**") "decks" and set a release limit after which all cards are automatically illegal (not released in this format) but could be manually placed onto an "unlimited" list so some newer cards could be explicitely allowed even if they are not on the (semi)limited list.

**Describe alternatives you've considered**
An importer that takes a simple CSV file that lists all cards in **forbidden**,  **limited**, and **semi-limited** (and newer **unlimited**) columns and asks for a release-date limit after import.

**Additional context**
Related to #131

**Comment by r0adkll** [comment]
Please see my comment on https://github.com/r0adkll/DeckBox/issues/131
