### ISSUE TITLE
[MISSING CARDS] Is this app dead? What about fixing bugs, add new sets etc.?

### ISSUE THREAD

**Issue by tkantor81** [r0adkll/DeckBox#133]
Will be ever added cards from Shining Fate set?
No cards, only expansion title has been added to the app.

**Comment by r0adkll** [comment]
It looks like some change from the API (pokemontcg.io) has broken my SDK and causing the current application to fail in loading the new set of cards and causing searches to fail if they return any of these new cards. 

I do have plans to fix this bug and others that I have in the pipeline but unfortunately, I'm the only developer on this project and I just haven't had the time between this, my other projects, and my day job.

I wouldn't call this project dead yet, but I can't promise any deadlines. I do plan to update its design to be closer to its Yu-Gi-Oh! brother that I built (https://play.google.com/store/apps/details?id=com.ygoprodeck.app). I apologize that this project has been so stagnant and I do plan to update in the near future.
