### ISSUE TITLE
Astral Radiance is Missing 

### ISSUE THREAD

**Issue by RevCameron** [r0adkll/DeckBox#142]
## Describe the missing card

* **Set:** Astral Radiance 
* **Name:** All
* **Number:** All

**Comment by RevCameron** [comment]
Please get this fixed ASAP, I have a tournament this weekend and don't want to do my decklist by hand...

**Comment by danilose** [comment]
@RevCameron you just need to go in the Browse menu end pull down to refresh, them the newest sets will appear

**Comment by RevCameron** [comment]
I figured that out. Now I have a new issue that the amount of cards that I
have in collections doesn't save correctly.

**Comment by danilose** [comment]
@RevCameron please close this issue and open another one with more information about the problem and if you could attach some screenshots
